### ISSUE TITLE
Problem with "dump-dataflash", "upload-logo" and evic-convert

### ISSUE THREAD

**Issue by Musik234** [Ban3/python-evic#12]
I have python-evic installed on linux mint 17.1
The old version "evic convert ..." and "evic upload ..."worked.
After pulling the update "evic-usb upload ..." still works.
But now "evic-convert", "evic-usb dump-dataflash" and "evic-usb upload-logo" are showing errors:
evic-convert ...
[evic-convert.txt](https://github.com/Ban3/python-evic/files/233485/evic-convert.txt)
evic-usb dump-dataflash
[dump-dataflash.txt](https://github.com/Ban3/python-evic/files/233488/dump-dataflash.txt)
evic-usb upload-logo
[upload-logo.txt](https://github.com/Ban3/python-evic/files/233489/upload-logo.txt)
To be honest, my linux skills are quite poor, so I don't know what to do.

**Comment by Ban3** [comment]
Your issue with `dump-dataflash` and `evic-convert` comes from a missing option, (`--output`). The correct format is: `evic-convert eVic_VTC_Mini_V3.00.bin -o output.bin`. `dump-dataflash` has the same option. I fixed it throwing that exception in fe449898d0d.

I suspect the issue with `upload-logo` comes from a old version of Pillow. Make sure you have the latest by installing with pip: `pip install pillow`

**Comment by Musik234** [comment]
"dump-dataflash" and "evic-convert" work with the right syntax.
"upload-logo" still does not work.

"pip install pillow":
[pip-install_pillow.txt](https://github.com/Ban3/python-evic/files/233600/pip-install_pillow.txt)
Then I thought, maybe "--upgrade" could help. Only works with "sudo":
[sudo_pip-install_pillow_--upgrade.txt](https://github.com/Ban3/python-evic/files/233602/sudo_pip-install_pillow_--upgrade.txt)
"evic-usb upload-logo Logo.bmp":
[upload-logo_2.txt](https://github.com/Ban3/python-evic/files/233604/upload-logo_2.txt)

BTW; is it correct, that evic-usb dump-dataflash -o dump.bin produces a file of only 2.044 bytes? Isn't that the whole firmware?

**Comment by ReservedField** [comment]
We noticed you have a very old PIL (2.3.0) which pip won't touch because it's owned by the OS. Try:

```
sudo apt-get remove python-imaging
sudo pip install pillow
```

**Comment by Ban3** [comment]
> BTW; is it correct, that evic-usb dump-dataflash -o dump.bin produces a file of only 2.044 bytes? Isn't that the whole firmware?

`dump-dataflash` only dumps the device data flash (user settings). Whole firmware can't be dumped through HID commands.

**Comment by Musik234** [comment]
After uninstalling python-imaging my desktop was gone because  "sudo apt-get remove python-imaging" wiped "cinnamon" from my hd. Just a black screen with a mouse pointer. ;-(
So I had to reinstall cinnamon which also reinstalled python-imaging. Looks like the cinnamon-desktop depends on python-imaging version 2.3.0

`dump-dataflash only dumps the device data flash (user settings). Whole firmware can't be dumped through HID commands.`
Hmmm, what a pity, I thought I could download the firmware from my new iStick pico to hack it.

**Comment by Ban3** [comment]
I think your only option is to try to override the system wide installation. Something like:

`pip install --user --ignore-installed pillow`

should work.

**Comment by Musik234** [comment]
Unfortunately not. :-(
While installing the following shows up:

> ---
> 
> ```
> PIL SETUP SUMMARY
> --------------------------------------------------------------------
> version      Pillow 3.2.0
> platform     linux2 2.7.6 (default, Jun 22 2015, 17:58:13)
>              [GCC 4.8.2]
> --------------------------------------------------------------------
> *** TKINTER support not available
> (Tcl/Tk 8.6 libraries needed)
> --- JPEG support available
> *** OPENJPEG (JPEG2000) support not available
> --- ZLIB (PNG/ZIP) support available
> --- LIBTIFF support available
> --- FREETYPE2 support available
> *** LITTLECMS2 support not available
> *** WEBP support not available
> *** WEBPMUX support not available
> --------------------------------------------------------------------
> To add a missing option, make sure you have the required
> library, and set the corresponding ROOT variable in the
> setup.py script.
> ```

Maybe the missing programs are the problem?

And somewhere in the net I found how to find out my version of pil:

> $ python
> Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > import PIL
> > > PIL.VERSION
> > > '1.1.7'

**Comment by Ban3** [comment]
PIL.VERSION is 1.1.7 with Pillow 3.2.0 as well. You need to check PIL.PILLOW_VERSION

**Comment by Musik234** [comment]
It's version 2.3.0. Looks like the override didn't work.

**Comment by Ban3** [comment]
I just merged #14 which removes the newer Pillow requirement. Can you try again with latest version.

**Comment by Musik234** [comment]
[python-setup.py-install.txt](https://github.com/Ban3/python-evic/files/233667/python-setup.py-install.txt)

Now the "evic-python upload ..." is broken.
[upload-firmware.txt](https://github.com/Ban3/python-evic/files/233668/upload-firmware.txt)

STOP, it works I had to reinstall libopenjpeg2.

**Comment by ReservedField** [comment]
I think it's a result of your misadventure with cinnamon (sorry about that, I assumed you'd stop it if it had dependencies). Seems like you're missing `sudo apt-get install openjpeg2`.

**Comment by Musik234** [comment]
OK, now it works fine.
I made something with the libopenjpeg2 in the meantime, but now after reinstalling it everything works fine. Thanks a lot.

**Comment by Ban3** [comment]
Great that is now working. You said earlier that you dumped dataflash from istick pico, could you attach the file to this issue? I could add the product code to the updater.

**Comment by Musik234** [comment]
Your wish is my command! :-)))

**Comment by Musik234** [comment]
Hmmm, I cannot add a .bin nor a .zip.
[iStick_pico.txt](https://github.com/Ban3/python-evic/files/233684/iStick_pico.txt)
But I can add a .txt ;-)
Just rename it to iStick_pico.bin

`$ evic-usb dump-dataflash -o iStick_pico.bin

Finding device...OK
    Manufacturer: Nuvoton
    Product: HID Transfer
    Serial No: A02014090xxx

Reading data flash...OK
    Device name: Unknown device
    Firmware version: 1.00
    Hardware version: 1.00

Writing data flash to the file...OK
`

**Comment by Musik234** [comment]
Some additional info:

$ lsusb
Bus 002 Device 012: ID 0416:5020 Winbond Electronics Corp. 

$ dmesg
[ 4971.748567] usb 2-1: new full-speed USB device number 13 using xhci_hcd
[ 4971.765564] usb 2-1: New USB device found, idVendor=0416, idProduct=5020
[ 4971.765576] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4971.765581] usb 2-1: Product: HID Transfer
[ 4971.765585] usb 2-1: Manufacturer: Nuvoton
[ 4971.765589] usb 2-1: SerialNumber: A02014090304
[ 4971.765824] usb 2-1: ep 0x81 - rounding interval to 128 microframes, ep desc says 160 microframes
[ 4971.765835] usb 2-1: ep 0x2 - rounding interval to 128 microframes, ep desc says 160 microframes
[ 4971.767036] input: Nuvoton HID Transfer as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/input/input25
[ 4971.767260] hid-generic 0003:0416:5020.000A: input,hidraw1: USB HID v1.10 Device [Nuvoton HID Transfer] on usb-0000:00:14.0-1/input0

**Comment by Ban3** [comment]
Thanks for the dataflash. Product added in ec0f3af16c53.

I'll close this issue as resolved.
